enum ACTIVITY_LEVEL {
  SEDENTARY = "SEDENTARY",
  LIGHTLY_ACTIVE = "LIGHTLY_ACTIVE",
  MODERATELY_ACTIVE = "MODERATELY_ACTIVE",
  VERY_ACTIVE = "VERY_ACTIVE",
}

enum DIETARY_PREFERENCE {
  VEGAN = "VEGAN",
  VEGETARIAN = "VEGETARIAN",
  NON_VEGETARIAN = "NON_VEGETARIAN",
}

enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
  OTHER = "OTHER",
}

enum GOAL_DURATION {
  SHORT_TERM = "SHORT_TERM",
  MEDIUM_TERM = "MEDIUM_TERM",
  LONG_TERM = "LONG_TERM",
}
enum GOAL_TYPE {
  WEIGHT_LOSS = "WEIGHT_LOSS",
  WEIGHT_GAIN = "WEIGHT_GAIN",
}

enum UNIT_SYSTEM {
  IMPERIAL = "IMPERIAL",
  METRIC = "METRIC",
}

export {
  ACTIVITY_LEVEL,
  DIETARY_PREFERENCE,
  GENDER,
  GOAL_DURATION,
  GOAL_TYPE,
  UNIT_SYSTEM,
};
